# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                  #{ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                  {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                  #{ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                  {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                  {ip: '10.1.1.1', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "central-net1"},
                  {ip: '10.1.2.1', adapter: 5, netmask: "255.255.255.252", virtualbox__intnet: "central-net2"},
                  {adapter: 6, auto_config: false, virtualbox__intnet: "dir-net"},
                  #{ip: '192.168.0.33', adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                  #{ip: '192.168.0.65', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "wi-fi-net"},                 
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  },

  :office1Router => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.1.1.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "central-net1"},
               {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"},
               {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testservers1-net"},
               {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "managers1-net"},
               {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hardware1-net"},
               {ip: '192.168.3.1', adapter: 7, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
            ]
  },

  :office1Server => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"},
               {adapter: 3, auto_config: false, virtualbox__intnet: true},
               {adapter: 4, auto_config: false, virtualbox__intnet: true},
            ]
},

  :testServer1 => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.3.2', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "test1-net"},
              {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLAN"},
            ]
  }, 

  :testClient1 => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.3.3', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
              {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLAN"},
            ]
  }, 

  :testServer2 => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.3.4', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
              {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLAN"},
            ]
  }, 

  :testClient2 => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.3.5', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
              {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLAN"},
            ]
  }, 

  :office2Router => {
    :box_name => "centos/7",
    :net => [
              {ip: '10.1.2.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "central-net2"},
              {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
              {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testservers2-net"},
              {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hardware2-net"},
            ]
  }, 

  :office2Server => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
               {adapter: 3, auto_config: false, virtualbox__intnet: true},
               {adapter: 4, auto_config: false, virtualbox__intnet: true},
            ]
},

  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
          when "inetRouter"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              cp /vagrant/network-scripts/ifcfg-bond0-inet /etc/sysconfig/network-scripts/ifcfg-bond0
              cp /vagrant/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts
              cp /vagrant/network-scripts/ifcfg-eth2 /etc/sysconfig/network-scripts
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              echo "192.168.0.0/16 via 192.168.255.2 dev bond0" >> /etc/sysconfig/network-scripts/route-bond0
              service network restart
              iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
              SHELL
          when "centralRouter"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              #systemctl restart network
              cp /vagrant/network-scripts/ifcfg-bond0-central /etc/sysconfig/network-scripts/ifcfg-bond0
              cp /vagrant/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts
              cp /vagrant/network-scripts/ifcfg-eth2 /etc/sysconfig/network-scripts
              cp /vagrant/network-scripts/ifcfg-eth5-central /etc/sysconfig/network-scripts/ifcfg-eth5
              cp /vagrant/network-scripts/ifcfg-eth5.0-central /etc/sysconfig/network-scripts/ifcfg-eth5:0
              cp /vagrant/network-scripts/ifcfg-eth5.1-central /etc/sysconfig/network-scripts/ifcfg-eth5:1
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              #echo "0.0.0.0/0 via 192.168.255.1 dev bond0" >> /etc/sysconfig/network-scripts/route-bond0
              #echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              #echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              systemctl restart network
              ip route add 192.168.2.0/24 via 10.1.1.2
              ip route add 192.168.1.0/24 via 10.1.2.2
              SHELL
          when "centralServer"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              SHELL
          when "office1Router"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=10.1.1.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              SHELL
          when "office1Server"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              SHELL
          when "testClient1"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              cp /vagrant/network-scripts/ifcfg-vlan2-client /etc/sysconfig/network-scripts/ifcfg-vlan2
              systemctl restart network
              SHELL
          when "testServer1"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              cp /vagrant/network-scripts/ifcfg-vlan2-server /etc/sysconfig/network-scripts/ifcfg-vlan2
              systemctl restart network
              SHELL
          when "testClient2"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              cp /vagrant/network-scripts/ifcfg-vlan3-client /etc/sysconfig/network-scripts/ifcfg-vlan3
              systemctl restart network
              SHELL
          when "testServer2"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              cp /vagrant/network-scripts/ifcfg-vlan3-server /etc/sysconfig/network-scripts/ifcfg-vlan3
              systemctl restart network
              SHELL
          when "office2Router"
              box.vm.provision "shell", run: "always", inline: <<-SHELL
                echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
                sysctl -p /etc/sysctl.conf
                echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
                echo "GATEWAY=10.1.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
                systemctl restart network
                SHELL
          when "office2Server"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.1.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              SHELL
          
        end

      end

  end
  
  
end
