# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {

  :R1 => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.12.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "vlan12"},
              {ip: '192.168.13.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "vlan13"},
              {ip: '10.1.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "AR0"},
            ]
  }, 

  :R2 => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.12.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "vlan12"},
              {ip: '192.168.23.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "vlan23"},
              {ip: '10.2.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "AR1"},
            ]
  }, 

  :R3 => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.13.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "vlan13"},
              {ip: '192.168.23.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "vlan23"},
              {ip: '10.3.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "AR2"},
            ]
  }, 


}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s

          when "R1"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
              systemctl restart network
              SHELL
          when "R2"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
              systemctl restart network
              SHELL
          when "R3"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
              systemctl restart network
              SHELL

        end

      end

  end
  
  
end
