# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

# only routers central and inetrouter and office1net

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                  {ip: '10.1.1.1', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "central-net1"},
                  {ip: '10.1.2.1', adapter: 5, netmask: "255.255.255.252", virtualbox__intnet: "central-net2"},
                  {adapter: 6, auto_config: false, virtualbox__intnet: "dir-net"},               
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
          when "inetRouter"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              cp /vagrant/network-scripts/ifcfg-bond0-inet /etc/sysconfig/network-scripts/ifcfg-bond0
              cp /vagrant/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts
              cp /vagrant/network-scripts/ifcfg-eth2 /etc/sysconfig/network-scripts
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              echo "192.168.0.0/16 via 192.168.255.2 dev bond0" >> /etc/sysconfig/network-scripts/route-bond0
              service network restart
              iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
              SHELL
          when "centralRouter"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              #systemctl restart network
              cp /vagrant/network-scripts/ifcfg-bond0-central /etc/sysconfig/network-scripts/ifcfg-bond0
              cp /vagrant/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts
              cp /vagrant/network-scripts/ifcfg-eth2 /etc/sysconfig/network-scripts
              cp /vagrant/network-scripts/ifcfg-eth5-central /etc/sysconfig/network-scripts/ifcfg-eth5
              cp /vagrant/network-scripts/ifcfg-eth5.0-central /etc/sysconfig/network-scripts/ifcfg-eth5:0
              cp /vagrant/network-scripts/ifcfg-eth5.1-central /etc/sysconfig/network-scripts/ifcfg-eth5:1
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              systemctl restart network
              ip route add 192.168.2.0/24 via 10.1.1.2
              ip route add 192.168.1.0/24 via 10.1.2.2
              SHELL

        end

      end

  end
  
  
end
