# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {

  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dir-net"},
                   
                ]
  },

  :office1Router => {
        :box_name => "centos/7",
        :net => [
                    {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dir-net"},
                ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s

          when "centralRouter"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              systemctl restart network
              iptables -A INPUT -p UDP --dport 1194 -j ACCEPT
              iptables -A OUTPUT -p udp --sport 1194 -j ACCEPT
              iptables -A FORWARD -s 10.10.0.0/24 -d 192.168.0.0/24 -j ACCEPT
              iptables -A FORWARD -d 10.10.0.0/24 -s 192.168.0.0/24 -j ACCEPT
              #ZADOLBAL!
              setenforce 0
              #Installing packets
              yum install -y epel-release
              yum install -y openvpn
              #Create server config
              echo "\
              dev tun0\
              ifconfig 10.10.10.1 10.10.10.2\
              secret /vagrant/emergency.key\
              comp-lzo\
              status /var/log/openvpn-status.log\
              log /var/log/openvpn.log\
              verb 3" > /etc/openvpn/server.conf
              #Service start
              systemctl start openvpn@server
              systemctl enable openvpn@server
              #Check status
              sleep 5
              systemctl status openvpn@server
              ip a
              SHELL
          when "office1Router"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              systemctl restart network
              iptables -A INPUT -p UDP --dport 1194 -j ACCEPT
              iptables -A OUTPUT -p udp --sport 1194 -j ACCEPT
              iptables -A FORWARD -s 10.10.0.0/24 -d 192.168.0.0/24 -j ACCEPT
              iptables -A FORWARD -d 10.10.0.0/24 -s 192.168.0.0/24 -j ACCEPT
              #ZADOLBAL!
              setenforce 0
              #Installing packets
              yum install -y epel-release
              yum install -y openvpn
              #Create server config
              echo "\
              dev tun0\
              remote 192.168.0.1\
              ifconfig 10.10.10.2 10.10.10.1\
              secret /vagrant/emergency.key\
              comp-lzo\
              status /var/log/openvpn-status.log\
              log /var/log/openvpn.log\
              verb 3" > /etc/openvpn/client.conf
              #Service start
              systemctl start openvpn@client
              systemctl enable openvpn@client
              #Check status
              sleep 5
              systemctl status openvpn@client
              echo "sleeping 10 sec"
              sleep 10
              ip a
              ping -c 5 10.0.10.1
              SHELL
          
        end
      end

  end
  
  
end
