# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {

  :web => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.1.1.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net"},

            ]
  },
  :log => {
    :box_name => "centos/7",
    :net => [
              {ip: '10.1.1.3', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net"},

            ]
  }, 
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 1024
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
      end

  end
  
  
end
