# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {

  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dir-net"},
                   
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dir-net"},

                ]
  },

  :office1Router => {
        :box_name => "centos/7",
        :net => [
                  {ip: '192.168.2.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dev1-net"},
                ]
  },

  :office1Server => {
        :box_name => "centos/7",
        :net => [
                  {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dev1-net"},

                ]
},
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        box.vm.synced_folder "temp/", "/srv"

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s

          when "centralRouter"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              systemctl restart network
              iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
              iptables -A INPUT -p UDP --dport 1194 -j ACCEPT
              iptables -A OUTPUT -p udp --sport 1194 -j ACCEPT
              iptables -A FORWARD -s 10.10.0.0/24 -d 192.168.0.0/24 -j ACCEPT
              iptables -A FORWARD -d 10.10.0.0/24 -s 192.168.0.0/24 -j ACCEPT
              ip route add 192.168.0.0/16 via 192.168.0.2
              chmod +x /srv/server.sh
              /srv/server.sh
              SHELL
          when "centralServer"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              SHELL
          when "office1Router"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              systemctl restart network
              chmod +x /srv/client.sh
              /srv/client.sh
              iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
              iptables -A INPUT -p UDP --dport 1194 -j ACCEPT
              iptables -A OUTPUT -p udp --sport 1194 -j ACCEPT
              iptables -A FORWARD -s 10.10.0.0/24 -d 192.168.0.0/24 -j ACCEPT
              iptables -A FORWARD -d 10.10.0.0/24 -s 192.168.0.0/24 -j ACCEPT
              ip route add 192.168.0.0/16 via 192.168.2.2
              SHELL
          when "office1Server"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              SHELL
          
        end
      end

  end
  
  
end
